### ISSUE TITLE
fastPut step 'total_transferred' always the same as 'total'

### ISSUE THREAD

**Issue by TrevorPT** [mscdex/ssh2-streams#27]
Hello.  Looking at the docs for sftp client fastPut:
>* fastPut(< string >localPath, < string >remotePath[, < object >options], < function >callback) - (void) - Uploads a file from localPath to remotePath using parallel reads for faster throughput. options can have the following properties:
>
>    concurrency - integer - Number of concurrent reads Default: 25
>
>    chunkSize - integer - Size of each read in bytes Default: 32768
>
>    step - function(< integer >total_transferred, < integer >chunk, < integer >total) - Called every time a part of a file was transferred
>
>callback has 1 parameter: < Error >err.

1. I'm guessing it should be 'writes' where it says 'reads'.

2. I'm trying it as follows:
```javascript
sftp.fastPut( localPath, remotePath, {
        step: function ( totalTx, chunk, total ) {
            console.log( 'uploadFile.step totalTx', totalTx, 'chunk', chunk, 'total', total );
        }
    },
```
and getting the following output for a file of 106614 bytes:
```
uploadFile.step totalTx 106614 chunk 32768 total 106614
uploadFile.step totalTx 106614 chunk 32768 total 106614
uploadFile.step totalTx 106614 chunk 32768 total 106614
uploadFile.step totalTx 106614 chunk 8310 total 106614
```
The "totalTx" ("total_transferred") appears to be the same value as the "total"; is this correct?  Is there no running total of "bytes transferred so far"?  I can easily calculate it myself but then I'm wondering why there are two "total" parameters.

Thanks!

**Comment by mscdex** [comment]
1. Well, it's parallel reads or writes depending on what side you're looking at it from. For `fastPut()` it's parallel reads from disk, but parallel writes to the remote server.

2. This behavior is changed in 7c1e3a95a8. Basically there wasn't anything really wrong, it's just that previously, the `totalTx` value was incremented _before_ the write callback fired. So if you had a small enough file and/or the entire transfer happened very quickly, you could easily see `totalTx === total`. However, if you try with a much larger file, you will see that the value would actually vary.

However now I have moved it so that the total transferred value doesn't increment until the write callback is called.

Let me know if that works for you.

**Comment by TrevorPT** [comment]
1. Ahh, understood.  I wasn't thinking of both sides of the connection.
2. Yep, with that change it now works the way I was expecting:
```
uploadFile.step totalTx 32768 chunk 32768 total 106614
uploadFile.step totalTx 65536 chunk 32768 total 106614
uploadFile.step totalTx 98304 chunk 32768 total 106614
uploadFile.step totalTx 106614 chunk 8310 total 106614
```
Thanks very much!
