### ISSUE TITLE
ECDSA support

### ISSUE THREAD

**Issue by ChaoticMind** [mscdex/ssh2-streams#3]
Are there any plans for ecdsa support?

**Comment by mscdex** [comment]
Sure, provided node/iojs's crypto interface supports them.

**Comment by elbertcastaneda** [comment]
I need your help, i have this error when try to connect :

ERROR:nw_shell.cc(335)] Error: Bad packet length
    at SSH2Stream._transform

**Comment by mscdex** [comment]
@elbertcastaneda Your issue is unrelated to the original issue, please file a *new* issue [here](https://github.com/mscdex/ssh2/issues).

**Comment by appsforartists** [comment]
@mscdex Should I be able to use ecdsa keys with ssh-agent?  I've got these two keys:

```
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp256
```

that result in `"Agent key #1 failed"` (and `#2`).  These are the handshake protocols I see if I put a logger in `DEBUG_NOOP`:

    diffie-hellman-group-exchange-sha256
    ssh-rsa
    aes256-ctr
    hmac-sha1
    none

**Comment by mscdex** [comment]
@appsforartists No, not currently.

**Comment by appsforartists** [comment]
@mscdex Thanks and :cry: 

You mentioned earlier that the blocker was a lack of support in Node's [crypto](https://nodejs.org/api/crypto.html#crypto_crypto_setengine_engine_flags) library.  I see references to EDSCA in crypto's [`setEngine` method](https://nodejs.org/api/crypto.html#crypto_crypto_setengine_engine_flags).  There's also [this library](https://github.com/cryptocoinjs/secp256k1-node) based on the work of Node.js core member @indutny.  Do either of those pave the way for ecdsa support in ssh2.js?

**Comment by mscdex** [comment]
@appsforartists The problem is that node does support ECDSA and other algorithms that might be useful for `ssh2`, but it's supported at the *TLS* level. The `crypto` module itself has to be provide access to those algorithms, which is not always automatic. I haven't looked recently to see if `crypto` now provides this kind of access in node v4+ or not.

There are a number of node addons that provide various algorithm implementations, but the problem is just that: they're addons, meaning they require a compiler. One of the goals is to remain "pure js," but this topic has been discussed before. I probably wouldn't mind adding such addons as *optionalDependency*s and possibly falling back to a pure js implementation. The benefit there being that compiled addons would be faster. However, these kinds of changes wouldn't come until configurable algorithms are supported (right now the algorithms and their order are more or less hard coded).

**Comment by mscdex** [comment]
After further research it looks like ECDSA support has existed in node since the node v0.11.x days. I have added (working) support for it in `ssh2`/`ssh2-streams`, but it needs actual tests yet.

**Comment by mscdex** [comment]
ECDSA is different than EdDSA. ECDSA has been supported for awhile now. EdDSA will require at least node v12.x (not released as of this writing) for the time being.
