### ISSUE TITLE
Pb with fastGet on a server responding to an fstat with size flag and size value equal to 0

### ISSUE THREAD

**Issue by fundkis** [mscdex/ssh2-streams#36]
We had to download files from a server which has an issue with fstat because in the fstat response, it sets the size flag and set the size value to 0 whereas the file is not empty.
fastXfer (and thus fastGet) will fallback to stat if fstat returns an error but since there is no error and fstat returns 0 it just goes throw the normal logic which... does not handle empty files (this is another issue because some may care about getting empty files...)
So, to workaround this problem, we just added in sftp.js on line 473 this code:
`if (attrs.size === 0) {
                cb('file size is equal to 0');
              } else {
                cb(undefined, attrs);
              }`
the fallback logic is implemented in different places. I just patched the fastXfer method. I think it'll be better if there is a doYourBestStat method centralizing the fallback logic.
I think also that the library should propose a configuration option to just skip fstat altogether if we know a specific server does not implement it correctly.

do you want me to submit a PR?

**Comment by mscdex** [comment]
`fastGet()`/fastPut()` were added as convenience methods for doing parallel reads/writes. They are not meant to satisfy everyone's use case, even though more API has been added to it over time...

If you expect to be connecting to SFTP servers that misbehave in the way you describe, you will probably be better off with your own `fastGet()` implementation, since who is to say that `stat()` wouldn't "lie" also or `fstat()` could reply with a non-zero but incorrect value? There is only so much you can do for buggy *servers*.

If you want to submit a PR to fix an issue with empty files, I would be open to that for sure.
