### ISSUE TITLE
sftp read/write, howto return error on invalid handle ?

### ISSUE THREAD

**Issue by andelo** [mscdex/ssh2-streams#7]
From the spec: section 8.2. "Reading and Writing" says 'the server MUST return SSH_FX_INVALID_HANDLE' if the handle passed from the client is invalid. 

How do you return these types of error codes to the client?

**Comment by mscdex** [comment]
There is no `SSH_FX_INVALID_HANDLE` message for the [SFTPv3 protocol](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#page-21). That particular status code is only available for SFTPv4+, which this module does not support (currently) since v3 is the most commonly implemented version. The RFC-defined [status codes](https://github.com/mscdex/ssh2-streams/blob/739bff7b9ed99c11112bda04fb181f42dc04038c/lib/sftp.js#L28-L36) for v3 are available on [`SFTPStream.STATUS_CODE`](https://github.com/mscdex/ssh2-streams/blob/739bff7b9ed99c11112bda04fb181f42dc04038c/lib/sftp.js#L40).

**Comment by andelo** [comment]
Oh thanks for making that clear, I was looking at "draft-ietf-secsh-filexfer-13.txt" from July 10, 2006.
SFTPStrem.STATUS_CODE should then just need ```INVALID_HANDLE: 9```.

**Comment by maboiteaspam** [comment]
Hi,

i found a situation where i was looking for that.

I tried to open an handle on a file owned by root, as a simple user (vagrant).

The stream would not terminate, nor emit an error.

I d like to know if you think this is related and if you d like to re consider this behavior or if i should simply implement a sort of timeout on my side.

Thanks !

**Comment by mscdex** [comment]
@maboiteaspam It seems that may be a separate issue as you are discussing using `ssh2-streams` as a client and not as a server like @andelo. If you could, please open a new issue and also include a simple, reproducible example in the description.

**Comment by maboiteaspam** [comment]
Ok cool, i ll prepare that and land it somewhere for your review. thanks!
